[WIP] SDK integration
YaronKoller/envoy pull request #10
Opened 2020-08-27 22:45 UTC by h9jiang

For an explanation of how to fill out the fields, please see the relevant section
in [PULL_REQUESTS.md](https://github.com/envoyproxy/envoy/blob/master/PULL_REQUESTS.md)

Commit Message: Integrate SDK in to envoy. Using SDK to bind & unbind cloud event. 
Additional Description: Basically wrap things up for filter's functionality. 
Risk Level: Low
Testing: Unit Test & Integration Test
Docs Changes:
Release Notes:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Deprecated:]

2020-09-02 21:26 UTC, h9jiang commented on source/extensions/filters/http/gcp_events_convert/gcp_events_convert_filter.cc
> +  }
Using `Binder` to unbind and bind cloud event. Will finally generate a `boost::beast::HttpRequest` instead of using the example `HttpRequest` hard coded.

2020-09-07 20:05 UTC, YaronKoller requested changes

2020-09-07 20:46 UTC, hrasadi commented on bazel/repository_locations.bzl
> +        urls = ["https://github.com/michlee1337/cloudevents-sdk-cpp/archive/{version}.tar.gz"],
All PRs on the main repo is now merged. Please point to that repo.

2020-09-07 20:47 UTC, hrasadi requested changes
Please address Yaron's comments. Otherwise LGTM

2020-09-07 22:31 UTC, h9jiang commented on source/extensions/filters/http/gcp_events_convert/BUILD
> +        "@com_github_cloudevents_sdk//v1/protocol_binding:binder_lib",
It is not. I will remove them.

2020-09-07 22:34 UTC, h9jiang commented on source/extensions/filters/http/gcp_events_convert/gcp_events_convert_filter.cc
>    if (!update_status.ok()) {
Yes that make sense. Basically, if there is anything with the conversion, the SDK will give me some a wrong status code. If the SDK didn't report anything, I believe update function will never go wrong. At the end of the day, what they are trying to do is just copy & paste.

2020-09-07 22:57 UTC, h9jiang commented
[CHANGE](https://github.com/YaronKoller/envoy/pull/10/files/0145be228eaa29e1a56a25413727e6d9019c1573..8f5022c863c06249b340b7d8129d1fbfbe5d3b21) since you last review.

2020-09-07 22:59 UTC, h9jiang commented on source/extensions/filters/http/gcp_events_convert/gcp_events_convert_filter.cc
> +  updateBody(*req);
The reason why I didn't glue them together as one update function: 
1. In the next PR, update body take both the buffered data and the incoming data. 
2. It may be more straight forward to see the functionality of both the function

2020-09-09 15:56 UTC, YaronKoller approved these changes

2020-09-09 15:56 UTC, YaronKoller commented on bazel/repository_locations.bzl
>          project_name = "Cloudevents SDK",
```suggestion
        project_name = "CloudEvents SDK",
```

2020-09-15 02:36 UTC, hrasadi approved these changes

2020-09-15 02:36 UTC, merged