incorporate grpc_stream_demuxer proto
YaronKoller/envoy pull request #8
Opened 2020-08-20 19:29 UTC by vmunukutla

Commit Message: incorporate grpc_stream_demuxer proto
Additional Description: I created a proto object for the GrpcStreamDemuxer, allowing the user to pass in the grpc_stream_demuxer config in their yaml config file such that a GrpcStreamDemuxer with the attributes passed in the yaml is initialized.
Risk Level: Medium
Testing: Unit testing
Docs Changes: None
Release Notes: None
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Deprecated:]

2020-09-07 17:46 UTC, YaronKoller requested changes
Looks good, mostly small things to fix.
Also:

1. Make sure you run the formatting script before sending out a PR.
2. Your commit history seems to be a bit mixed up? Or maybe just the link in the description is wrong, because I see some changes from your previous PR. This isn't a big deal, but maybe ask Jerry how he organizes his PRs.

2020-09-07 17:46 UTC, YaronKoller commented on source/server/configuration_impl.cc
> +  initializeGrpcStreamDemuxers(bootstrap);
This `MainImpl::initialize()` method probably has unit tests, right?
I think it'd be worth adding a couple test cases for the `GrpcStreamDemuxer` to it.

2020-09-07 17:46 UTC, YaronKoller commented on test/extensions/grpc_stream_demuxer/grpc_stream_demuxer_test.cc
> +}
When writing unit tests, try to focus on testing the source code that you wrote (i.e. code inside functions/methods).
To me, the above 2 test cases seem to be testing `loadFromYaml()`... I'm guessing you wanted to test the proto itself, but that's not really possible or necessary :)
I think it's safe to remove these 2 tests.

2020-09-07 17:46 UTC, YaronKoller commented on test/extensions/grpc_stream_demuxer/grpc_stream_demuxer_test.cc
> +  auto& factory = Config::Utility::getAndCheckFactoryByName<Envoy::GrpcStreamDemuxer::GrpcStreamDemuxerFactory>("grpc_stream_demuxer");
Didn't you change the namespace for `GrpcStreamDemuxerFactory`?
This shouldn't even compile anymore :)

2020-09-07 17:46 UTC, YaronKoller commented on test/extensions/grpc_stream_demuxer/grpc_stream_demuxer_test.cc
>  }
Similarly to above, I think this test case just tests `getAndCheckFactoryByName()`, which isn't very useful for us.

2020-09-07 17:46 UTC, YaronKoller commented on test/extensions/grpc_stream_demuxer/grpc_stream_demuxer_test.cc
> +  envoy::extensions::grpc_stream_demuxer::v3alpha::GrpcStreamDemuxer demuxer_object;
Please rename `demuxer_object` throughout this file too.

2020-09-07 19:03 UTC, vmunukutla commented on source/server/configuration_impl.cc
> +  initializeGrpcStreamDemuxers(bootstrap);
The code in my next PR is better suited for me to add unit tests for the MainImpl::initialize() method. Should I just add them there or incorporate some of the code for my next PR into this one?

2020-09-07 21:28 UTC, YaronKoller requested changes

2020-09-07 21:28 UTC, YaronKoller commented on source/server/configuration_impl.cc
> +  initializeGrpcStreamDemuxers(bootstrap);
Hmm, good question.
I don't want you to add a lot of stuff to this PR, so maybe just add the part where you maintain a list of demuxers?
Checking that demuxers were created should be enough for this unit test, since the demuxer class has its own unit tests.

2020-09-09 15:43 UTC, YaronKoller approved these changes

2020-09-15 02:35 UTC, hrasadi approved these changes

2020-09-15 02:35 UTC, merged